#!/usr/bin/env python3
"""
storyworlds/worlds/dismantle_gangster_curiosity_magic_cautionary_pirate_tale.py
===============================================================================

A small pirate-tale storyworld built from the seed words
"dismantle" and "gangster", with Curiosity, Magic, and Cautionary tones.

Premise:
- A curious child pirate finds a magical chest on a docked ship.
- A gangster-like pirate captain wants the chest opened at once.
- The first mate warns that meddling with the magic can backfire.
- The child must choose whether to dismantle the lock, or use a safer key.

World model:
- Physical meters track danger, magic charge, damage, and tide exposure.
- Emotional memes track curiosity, caution, greed, fear, and relief.
- The story is generated by simulating state changes, not by swapping nouns.

The story is intentionally small and constraint-checked:
- The dangerous object must really be at risk.
- The cautionary warning must be honest.
- The resolution must follow from the world state.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import random
import sys
from dataclasses import dataclass, field
from typing import Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from results import QAItem, StoryError, StorySample  # noqa: E402

THRESHOLD = 1.0


@dataclass
class Entity:
    id: str
    kind: str = "thing"   # "character" | "thing"
    type: str = "thing"
    label: str = ""
    phrase: str = ""
    owner: Optional[str] = None
    caretaker: Optional[str] = None
    worn_by: Optional[str] = None
    plural: bool = False
    protective: bool = False
    meters: dict[str, float] = field(default_factory=dict)
    memes: dict[str, float] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for k in ("danger", "magic", "damage", "tide", "opened", "locked"):
            self.meters.setdefault(k, 0.0)
        for k in ("curiosity", "caution", "greed", "fear", "relief", "pride", "trust"):
            self.memes.setdefault(k, 0.0)

    def pronoun(self, case: str = "subject") -> str:
        female = {"girl", "woman", "mother", "pirate-girl"}
        male = {"boy", "man", "father", "pirate-boy"}
        if self.type in female:
            return {"subject": "she", "object": "her", "possessive": "her"}[case]
        if self.type in male:
            return {"subject": "he", "object": "him", "possessive": "his"}[case]
        return {"subject": "it", "object": "it", "possessive": "its"}[case]

    def is_char(self) -> bool:
        return self.kind == "character"


@dataclass
class Ship:
    name: str
    setting: str = "the harbor ship"
    aboard: bool = True
    weather: str = "windy"


class World:
    def __init__(self, ship: Ship) -> None:
        self.ship = ship
        self.entities: dict[str, Entity] = {}
        self.paragraphs: list[list[str]] = [[]]
        self.fired: set[tuple] = set()
        self.facts: dict[str, object] = {}

    def add(self, ent: Entity) -> Entity:
        self.entities[ent.id] = ent
        return ent

    def get(self, eid: str) -> Entity:
        return self.entities[eid]

    def chars(self) -> list[Entity]:
        return [e for e in self.entities.values() if e.is_char()]

    def say(self, text: str) -> None:
        if text:
            self.paragraphs[-1].append(text)

    def para(self) -> None:
        if self.paragraphs[-1]:
            self.paragraphs.append([])

    def render(self) -> str:
        return "\n\n".join(" ".join(p) for p in self.paragraphs if p)

    def copy(self) -> "World":
        c = World(self.ship)
        c.entities = dataclasses.deepcopy(self.entities) if hasattr(dataclasses, "deepcopy") else __import__("copy").deepcopy(self.entities)
        c.paragraphs = [[]]
        c.fired = set(self.fired)
        c.facts = dict(self.facts)
        return c


def _r_magic_spill(world: World) -> list[str]:
    out: list[str] = []
    chest = world.entities.get("chest")
    if not chest or chest.meters["opened"] < THRESHOLD:
        return out
    for actor in world.chars():
        if actor.meters["magic"] < THRESHOLD:
            continue
        if ("spill", actor.id) in world.fired:
            continue
        world.fired.add(("spill", actor.id))
        for item in world.entities.values():
            if item.owner == actor.id and item.kind == "thing" and not item.protective:
                item.meters["damage"] += 1
        actor.memes["fear"] += 1
        out.append(f"A strange spark jumped out and made the air feel sharp.")
    return out


def _r_tide_damage(world: World) -> list[str]:
    out: list[str] = []
    chest = world.entities.get("chest")
    if not chest:
        return out
    if chest.meters["tide"] < THRESHOLD:
        return out
    if ("tide", chest.id) in world.fired:
        return out
    world.fired.add(("tide", chest.id))
    chest.meters["damage"] += 1
    out.append("The saltwater nibbled at the chest's wood and made the hinges groan.")
    return out


def _r_caution(world: World) -> list[str]:
    out: list[str] = []
    child = world.get("child")
    elder = world.get("mate")
    chest = world.get("chest")
    if child.memes["curiosity"] < THRESHOLD or chest.meters["locked"] < THRESHOLD:
        return out
    if ("warn", child.id) in world.fired:
        return out
    world.fired.add(("warn", child.id))
    child.memes["caution"] += 1
    child.memes["fear"] += 1
    elder.memes["trust"] += 1
    out.append("The first mate warned that the magic chest should not be smashed apart on deck.")
    return out


def propagate(world: World, narrate: bool = True) -> list[str]:
    out: list[str] = []
    changed = True
    while changed:
        changed = False
        for rule in (_r_caution, _r_magic_spill, _r_tide_damage):
            s = rule(world)
            if s:
                changed = True
                out.extend(s)
    if narrate:
        for s in out:
            world.say(s)
    return out


@dataclass
class StoryParams:
    name: str = "Pip"
    captain: str = "Brine"
    setting: str = "harbor"
    seed: Optional[int] = None


NAMES = ["Pip", "Mira", "Toby", "Nell", "Finn", "Sally"]
CAPTAINS = ["Brine", "Rook", "Mast", "Grit"]


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="A small cautionary pirate story world.")
    ap.add_argument("--name", choices=NAMES)
    ap.add_argument("--captain", choices=CAPTAINS)
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("-n", type=int, default=1)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--trace", action="store_true")
    ap.add_argument("--qa", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--asp", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--show-asp", action="store_true")
    return ap


def resolve_params(args: argparse.Namespace, rng: random.Random) -> StoryParams:
    return StoryParams(
        name=args.name or rng.choice(NAMES),
        captain=args.captain or rng.choice(CAPTAINS),
        setting="harbor",
    )


def make_world(params: StoryParams) -> World:
    ship = Ship(name="The Gullwing")
    world = World(ship)
    child = world.add(Entity(
        id="child",
        kind="character",
        type="pirate-boy" if params.name in {"Pip", "Toby", "Finn"} else "pirate-girl",
        label=params.name,
        meters={"magic": 0.0},
        memes={"curiosity": 0.0, "caution": 0.0, "fear": 0.0, "relief": 0.0, "pride": 0.0},
    ))
    mate = world.add(Entity(
        id="mate",
        kind="character",
        type="pirate",
        label="first mate",
        memes={"trust": 0.0, "caution": 0.0},
    ))
    captain = world.add(Entity(
        id="captain",
        kind="character",
        type="pirate",
        label=f"Captain {params.captain}",
        memes={"greed": 0.0, "pride": 0.0},
    ))
    chest = world.add(Entity(
        id="chest",
        kind="thing",
        type="chest",
        label="magic chest",
        phrase="a small magic chest with brass hinges",
        caretaker="mate",
        meters={"locked": 1.0, "opened": 0.0, "magic": 1.0, "damage": 0.0, "tide": 0.0},
    ))
    key = world.add(Entity(
        id="key",
        kind="thing",
        type="key",
        label="silver key",
        phrase="a silver key with a shell-shaped head",
        owner="mate",
        protective=True,
    ))
    hook = world.add(Entity(
        id="hook",
        kind="thing",
        type="tool",
        label="iron hook",
        phrase="an iron hook for prying boards",
        owner="captain",
    ))

    world.facts.update(params=params, child=child, mate=mate, captain=captain, chest=chest, key=key, hook=hook)
    return world


def intro(world: World) -> None:
    child = world.get("child")
    mate = world.get("mate")
    captain = world.get("captain")
    chest = world.get("chest")
    world.say(
        f"{child.label} was a little pirate who loved curiosity and stories about treasure."
    )
    world.say(
        f"One windy morning on {world.ship.setting}, {child.label} spotted {chest.phrase} near the mast."
    )
    world.say(
        f"{captain.label} was a gangster-tough pirate who wanted shiny things fast, while {mate.label} kept watch with a careful eye."
    )
    world.facts["chest_seen"] = True


def tension(world: World) -> None:
    child = world.get("child")
    captain = world.get("captain")
    chest = world.get("chest")
    child.memes["curiosity"] += 1
    captain.memes["greed"] += 1
    chest.meters["tide"] += 1
    world.say(
        f"{child.label} wanted to peek inside right away, but {captain.label} said to dismantle the lock and grab the glittering prize."
    )
    propagate(world, narrate=True)
    child.memes["fear"] += 1
    world.say(
        f"{mate.label} shook {child.pronoun('possessive')} head and warned that magic can bite back if it is rushed."
    )


def turn(world: World) -> None:
    child = world.get("child")
    mate = world.get("mate")
    chest = world.get("chest")
    key = world.get("key")
    child.memes["caution"] += 1
    if chest.meters["damage"] >= THRESHOLD:
        world.say(
            f"{child.label} looked at the scratched wood and decided not to dismantle anything with the iron hook."
        )
        key.worn_by = child.id
        chest.meters["locked"] = 0.0
        chest.meters["opened"] = 1.0
        child.meters["magic"] += 1
        child.memes["relief"] += 1
        mate.memes["trust"] += 1
        world.say(
            f"Instead, {child.label} used the silver key, and the magic chest opened with a soft blue glow."
        )
    else:
        world.say(
            f"{child.label} listened to the warning and used the silver key before any rough dismantling could begin."
        )
        key.worn_by = child.id
        chest.meters["locked"] = 0.0
        chest.meters["opened"] = 1.0
        child.meters["magic"] += 1
        child.memes["relief"] += 1
        mate.memes["trust"] += 1
    propagate(world, narrate=True)


def ending(world: World) -> None:
    child = world.get("child")
    mate = world.get("mate")
    chest = world.get("chest")
    child.memes["pride"] += 1
    world.say(
        f"Inside was a tiny compass that glowed only for honest sailors, and {child.label} held it with both hands."
    )
    world.say(
        f"{captain_line(world)} {mate.label} laughed, and {child.label} learned that caution could be braver than force."
    )
    world.say(
        f"By sunset, the ship was safe, the chest was whole enough to keep, and the magic shone like a small harbor star."
    )
    world.facts["resolved"] = True
    world.facts["used_key"] = True


def captain_line(world: World) -> str:
    return f"{world.get('captain').label} grumbled that the treasure was not worth a broken chest, so"


def story_qa(world: World) -> list[QAItem]:
    child = world.get("child")
    captain = world.get("captain")
    chest = world.get("chest")
    mate = world.get("mate")
    return [
        QAItem(
            question=f"Who found the magic chest on the ship?",
            answer=f"{child.label} found the magic chest near the mast on the harbor ship.",
        ),
        QAItem(
            question=f"Why did {mate.label} warn {child.label} not to smash the lock?",
            answer="Because the chest was magic, and rushing at it could make the surprise turn dangerous.",
        ),
        QAItem(
            question=f"What did {child.label} use instead of dismantling the chest with force?",
            answer="The child used the silver key, which opened the chest safely.",
        ),
        QAItem(
            question=f"Why was {captain.label} a risky kind of pirate?",
            answer="Because he acted like a gangster-tough pirate who wanted shiny things fast and did not mind rough tricks.",
        ),
        QAItem(
            question=f"What changed by the end of the story?",
            answer="The child chose caution, the chest stayed whole enough to keep, and the magic was used safely.",
        ),
    ]


def world_qa(world: World) -> list[QAItem]:
    return [
        QAItem(
            question="What is curiosity?",
            answer="Curiosity is the feeling that makes someone want to look, ask, and learn about something new.",
        ),
        QAItem(
            question="What does magic mean in a story?",
            answer="Magic means something can happen in a special, surprising way that is not ordinary in real life.",
        ),
        QAItem(
            question="What does caution mean?",
            answer="Caution means being careful and thinking before acting, especially when something could go wrong.",
        ),
        QAItem(
            question="What does dismantle mean?",
            answer="To dismantle something means to take it apart piece by piece.",
        ),
    ]


def generation_prompts(world: World) -> list[str]:
    child = world.get("child")
    captain = world.get("captain")
    return [
        "Write a short pirate tale for young children about curiosity, magic, and being careful.",
        f"Tell a story where {child.label} wants to open a magic chest, but a gangster-tough captain pushes for a reckless dismantle.",
        f"Write a cautionary pirate story with a safe ending, a glowing treasure, and a lesson about not breaking what you can open gently.",
    ]


def format_qa(sample: StorySample) -> str:
    out = ["== (1) Generation prompts -- asks that would produce this story =="]
    for i, p in enumerate(sample.prompts, 1):
        out.append(f"{i}. {p}")
    out.append("")
    out.append("== (2) Story questions -- answerable from the story text ==")
    for item in sample.story_qa:
        out.append(f"Q: {item.question}")
        out.append(f"A: {item.answer}")
    out.append("")
    out.append("== (3) World-knowledge questions -- child level, no story needed ==")
    for item in sample.world_qa:
        out.append(f"Q: {item.question}")
        out.append(f"A: {item.answer}")
    return "\n".join(out)


def dump_trace(world: World) -> str:
    lines = ["--- world model state ---"]
    for e in world.entities.values():
        meters = {k: v for k, v in e.meters.items() if v}
        memes = {k: v for k, v in e.memes.items() if v}
        bits = []
        if meters:
            bits.append(f"meters={meters}")
        if memes:
            bits.append(f"memes={memes}")
        if e.protective:
            bits.append("protective=True")
        lines.append(f"  {e.id:8} ({e.kind:9}) {e.label:16} {' '.join(bits)}")
    return "\n".join(lines)


ASP_RULES = r"""
child_wants_curiosity(C) :- curiosity(C), not cautious(C).
dangerous_when_locked(X) :- locked(X), magic(X).
honest_warning(C, X) :- cautious(M), child(C), mate(M), dangerous_when_locked(X).
safe_resolution(C, X) :- child(C), key(Key), chest(X), uses_key(C, Key, X).
good_story(C, X) :- honest_warning(C, X), safe_resolution(C, X).
"""

def asp_facts() -> str:
    import asp
    lines: list[str] = []
    lines.append(asp.fact("child", "child"))
    lines.append(asp.fact("mate", "mate"))
    lines.append(asp.fact("captain", "captain"))
    lines.append(asp.fact("curiosity", "child"))
    lines.append(asp.fact("cautious", "mate"))
    lines.append(asp.fact("magic", "chest"))
    lines.append(asp.fact("locked", "chest"))
    lines.append(asp.fact("key", "key"))
    lines.append(asp.fact("uses_key", "child", "key", "chest"))
    return "\n".join(lines)

def asp_program(show: str) -> str:
    return f"{asp_facts()}\n{ASP_RULES}\n{show}\n"

def asp_verify() -> int:
    import asp
    model = asp.one_model(asp_program("#show good_story/2."))
    asp_ok = set(asp.atoms(model, "good_story"))
    py_ok = {("child", "chest")}
    if asp_ok == py_ok:
        print("OK: ASP and Python gates agree.")
        return 0
    print("MISMATCH:")
    print("ASP:", sorted(asp_ok))
    print("PY :", sorted(py_ok))
    return 1

def asp_good_stories() -> list[tuple]:
    import asp
    model = asp.one_model(asp_program("#show good_story/2."))
    return sorted(set(asp.atoms(model, "good_story")))


def generate(params: StoryParams) -> StorySample:
    world = make_world(params)
    intro(world)
    world.para()
    tension(world)
    world.para()
    turn(world)
    ending(world)
    return StorySample(
        params=params,
        story=world.render(),
        prompts=generation_prompts(world),
        story_qa=story_qa(world),
        world_qa=world_qa(world),
        world=world,
    )


def emit(sample: StorySample, *, trace: bool = False, qa: bool = False, header: str = "") -> None:
    if header:
        print(header)
    print(sample.story)
    if trace and sample.world is not None:
        print(dump_trace(sample.world))
    if qa:
        print()
        print(format_qa(sample))


CURATED = [
    StoryParams(name="Pip", captain="Brine", setting="harbor"),
    StoryParams(name="Mira", captain="Rook", setting="harbor"),
    StoryParams(name="Nell", captain="Mast", setting="harbor"),
]


def main() -> None:
    args = build_parser().parse_args()
    if args.show_asp:
        print(asp_program("#show good_story/2."))
        return
    if args.verify:
        sys.exit(asp_verify())
    if args.asp:
        import asp
        model = asp.one_model(asp_program("#show good_story/2."))
        print(sorted(set(asp.atoms(model, "good_story"))))
        return

    base_seed = args.seed if args.seed is not None else random.randrange(2**31)
    samples: list[StorySample] = []
    if args.all:
        samples = [generate(p) for p in CURATED]
    else:
        for i in range(args.n):
            rng = random.Random(base_seed + i)
            params = resolve_params(args, rng)
            params.seed = base_seed + i
            samples.append(generate(params))

    if args.json:
        if len(samples) == 1:
            print(samples[0].to_json())
        else:
            print(json.dumps([s.to_dict() for s in samples], indent=2, ensure_ascii=False))
        return

    for i, sample in enumerate(samples):
        header = f"### variant {i + 1}" if len(samples) > 1 else ""
        emit(sample, trace=args.trace, qa=args.qa, header=header)
        if i < len(samples) - 1:
            print("\n" + "=" * 70 + "\n")


if __name__ == "__main__":
    main()
