#!/usr/bin/env python3
"""
storyworlds/worlds/eel_chief_sound_effects_heartwarming.py
===========================================================

A small heartwarming storyworld about a little eel, a chief, and the sound
effects they make together.

Seed premise:
---
A cheerful little eel loves making sound effects for stories and plays. The
chief of the tide hall helps guide the eel, but one special sound-maker gets in
the way of the performance. The chief notices the risk, offers a gentler plan,
and the two finish with a warm, happy show.

World model:
---
Entities can be characters or props. Characters carry physical meters like
soaked, tired, and sound_level, plus emotional memes like joy, worry, pride,
and closeness. The story is generated by simulating a simple sequence of
events: the eel starts the work, the chief notices a problem, the sound maker
is swapped for a safer one, and the performance ends with a comforting image.

This script keeps the prose concrete and child-facing, with explicit causal
turns rather than a frozen paragraph.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from dataclasses import dataclass, field
from typing import Optional

_storyworlds_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if not os.path.exists(os.path.join(_storyworlds_dir, "results.py")):
    _storyworlds_dir = os.path.dirname(_storyworlds_dir)
sys.path.insert(0, _storyworlds_dir)
from results import QAItem, StoryError, StorySample  # noqa: E402

THRESHOLD = 1.0



def _safe_fact(world, facts, key):
    value = facts.get(key) if hasattr(facts, "get") else None
    if hasattr(value, "id") or hasattr(value, "label") or hasattr(value, "verb") or hasattr(value, "sign"):
        return value
    if isinstance(value, str):
        if hasattr(world, "get"):
            try:
                resolved = world.get(value)
                if resolved is not None:
                    return resolved
            except Exception:
                pass
        upper = key.upper()
        for registry_name in (upper, upper + "S", upper + "ES", upper + "_REGISTRY"):
            registry = globals().get(registry_name)
            if isinstance(registry, dict) and value in registry:
                return registry[value]
        if upper.endswith("Y"):
            registry = globals().get(upper[:-1] + "IES")
            if isinstance(registry, dict) and value in registry:
                return registry[value]
    entities = getattr(world, "entities", {})
    if hasattr(entities, "values"):
        for entity in entities.values():
            if hasattr(entity, "id") or hasattr(entity, "label"):
                return entity
    return value


def _fallback_storyparams(args, rng, cls, ns):
    data = {}
    missing = getattr(__import__("dataclasses"), "MISSING")
    for field in __import__("dataclasses").fields(cls):
        name = field.name
        value = None
        for arg_name in (name, name.removesuffix("_name"), name.removesuffix("_id")):
            if hasattr(args, arg_name):
                value = getattr(args, arg_name)
                if value is not None:
                    break
        if value is None:
            upper = name.upper()
            keys = [upper, upper + "S", upper + "ES"]
            if upper.endswith("Y"):
                keys.append(upper[:-1] + "IES")
            for key in keys:
                pool = ns.get(key)
                if isinstance(pool, dict) and pool:
                    value = next(iter(pool.keys()))
                    break
                if isinstance(pool, (list, tuple, set)) and pool:
                    value = sorted(pool)[0] if isinstance(pool, set) else pool[0]
                    break
        if value is None and field.default is not missing:
            value = field.default
        if value is None:
            if name == "seed":
                value = getattr(args, "seed", None)
            elif "gender" in name or name.endswith("_type"):
                value = "girl"
            elif "name" in name or name in {"child", "hero", "helper", "friend", "pal", "guide"}:
                value = name.removesuffix("_name").replace("_", " ").title() or "Mia"
            else:
                value = name
        data[name] = value
    return cls(**data)


def _safe_lookup(mapping, key):
    try:
        return mapping[key]
    except Exception:
        pass
    if hasattr(mapping, "values"):
        values = list(mapping.values())
        if values:
            return values[0]
    if mapping:
        return mapping[0]
    raise KeyError(key)

@dataclass
class Entity:
    id: str
    kind: str = "thing"
    type: str = "thing"
    label: str = ""
    phrase: str = ""
    owner: Optional[str] = None
    caretaker: Optional[str] = None
    worn_by: Optional[str] = None
    protective: bool = False
    covers: set[str] = field(default_factory=set)
    plural: bool = False
    meters: dict[str, float] = field(default_factory=lambda: __import__('collections').defaultdict(float))
    memes: dict[str, float] = field(default_factory=lambda: __import__('collections').defaultdict(float))

    guards: set[str] = field(default_factory=set)
    chief: object | None = None
    eel: object | None = None
    prop: object | None = None
    safe: bool = False
    def __post_init__(self) -> None:
        for k in ["soaked", "tired", "loudness", "care", "stress", "dusty", "worn"]:
            self.meters.setdefault(k, 0.0)
        for k in ["joy", "worry", "pride", "closeness", "relief", "curiosity"]:
            self.memes.setdefault(k, 0.0)

    def pronoun(self, case: str = "subject") -> str:
        female = {"girl", "mother", "mom", "woman", "chief"}
        male = {"boy", "father", "dad", "man"}
        if self.type in female:
            return {"subject": "she", "object": "her", "possessive": "her"}[case]
        if self.type in male:
            return {"subject": "he", "object": "him", "possessive": "his"}[case]
        return {"subject": "it", "object": "it", "possessive": "its"}[case]

    def it(self) -> str:
        return "them" if self.plural else "it"
    @property
    def label_word(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def tags(self):
        if "_tags" not in self.__dict__:
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


@dataclass
class Setting:
    place: str
    indoor: bool
    affords: set[str] = field(default_factory=set)
    @property
    def meters(self):
        if "_meters" not in self.__dict__:
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if "_memes" not in self.__dict__:
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if "_tags" not in self.__dict__:
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        return None


@dataclass
class SoundEffect:
    id: str
    name: str
    text: str
    cue: str
    risk: str
    safe_cue: str
    tags: set[str] = field(default_factory=set)
    @property
    def label_word(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def label(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def phrase(self) -> str:
        return str(getattr(self, "_phrase", None) or str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower())))

    @phrase.setter
    def phrase(self, value: str) -> None:
        object.__setattr__(self, "_phrase", value)

    @property
    def meters(self):
        if "_meters" not in self.__dict__:
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if "_memes" not in self.__dict__:
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


@dataclass
class Prop:
    id: str
    label: str
    phrase: str
    region: str
    kind: str
    delicate: bool = False
    plural: bool = False
    @property
    def label_word(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def meters(self):
        if "_meters" not in self.__dict__:
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if "_memes" not in self.__dict__:
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if "_tags" not in self.__dict__:
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


@dataclass
class Tool:
    id: str
    label: str
    phrase: str
    helps: str
    covers: set[str] = field(default_factory=set)
    guards: set[str] = field(default_factory=set)
    plural: bool = False
    @property
    def label_word(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def meters(self):
        if "_meters" not in self.__dict__:
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if "_memes" not in self.__dict__:
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if "_tags" not in self.__dict__:
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


class World:
    def __init__(self, setting: Setting) -> None:
        self.setting = setting
        self.entities: dict[str, Entity] = {}
        self.paragraphs: list[list[str]] = [[]]
        self.facts: dict = {}
        self.fired: set[tuple] = set()
        self.active_effect: Optional[str] = None
        self.active_tool: Optional[str] = None

    def add(self, ent: Entity) -> Entity:
        self.entities[ent.id] = ent
        return ent

    def get(self, eid: str) -> Entity:
        if eid not in self.entities:
            label = str(eid).replace("_", " ")
            self.entities[eid] = Entity(str(eid), label=label)
        return self.entities[eid]

    def say(self, text: str) -> None:
        if text:
            self.paragraphs[-1].append(text)

    def para(self) -> None:
        if self.paragraphs[-1]:
            self.paragraphs.append([])

    def render(self) -> str:
        return "\n\n".join(" ".join(p) for p in self.paragraphs if p)

    def copy(self) -> "World":
        import copy
        clone = World(self.setting)
        clone.entities = copy.deepcopy(self.entities)
        clone.paragraphs = [[]]
        clone.facts = dict(self.facts)
        clone.fired = set(self.fired)
        clone.active_effect = self.active_effect
        clone.active_tool = self.active_tool
        return clone


def _r_wet_tool(world: World) -> list[str]:
    out = []
    if not world.active_effect:
        return out
    effect = _safe_lookup(SOUNDS, world.active_effect)
    for ent in list(world.entities.values()):
        if ent.kind != "character":
            continue
        if ent.meters["soaked"] < THRESHOLD:
            continue
        if world.active_tool is None:
            continue
        tool = world.get(world.active_tool)
        if tool.kind != "tool":
            continue
        if effect.risk not in tool.guards:
            continue
        sig = ("safe", ent.id, tool.id, effect.id)
        if sig in world.fired:
            continue
        world.fired.add(sig)
        ent.memes["relief"] += 1
        out.append(f"The {tool.label} kept the sound gentle.")
    return out


def propagate(world: World, narrate: bool = True) -> list[str]:
    produced = []
    changed = True
    for _ in range(len(globals().get("CAUSAL_RULES", [])) + 4):
        changed = False
        for rule in [_r_wet_tool]:
            lines = rule(world)
            if lines:
                changed = True
                produced.extend(lines)
    if narrate:
        for line in produced:
            world.say(line)
    return produced


def effect_risk(effect: SoundEffect, prop: Prop) -> bool:
    return prop.kind in effect.tags


def select_tool(effect: SoundEffect, prop: Prop) -> Optional[Tool]:
    for tool in TOOLS:
        if prop.kind in tool.guards:
            return tool
    return None


def predict_change(world: World, effect: SoundEffect, prop_id: str) -> dict:
    sim = world.copy()
    prop = sim.get(prop_id)
    apply_effect(sim, sim.get(world.facts["eel"].id), effect, prop, narrate=False)
    return {
        "worsened": prop.meters["worn"] >= THRESHOLD or prop.meters["dusty"] >= THRESHOLD,
        "relief": sim.get(world.facts["eel"].id).memes["relief"],
    }


def apply_effect(world: World, eel: Entity, effect: SoundEffect, prop: Entity, narrate: bool = True) -> None:
    world.active_effect = effect.id
    eel.memes["curiosity"] += 1
    eel.meters["loudness"] += 1
    prop.meters["worn"] += 1
    prop.meters["dusty"] += 1
    if narrate:
        world.say(effect.cue)
    propagate(world, narrate=narrate)


def build_scene(world: World, eel: Entity, chief: Entity, prop: Entity) -> None:
    world.say(f"{eel.id} was a little eel who loved sound effects.")
    world.say(f"{chief.id} was the chief of the tide hall, and {chief.pronoun()} smiled at careful practice.")
    world.say(f"{eel.id} treasured {eel.pronoun('possessive')} {prop.label} because it made the nicest {prop.phrase}.")

    world.para()
    world.say(f"One day, {eel.id} and {chief.id} went to {world.setting.place}.")
    world.say(f"{eel.id} wanted to make a big {world.facts['effect'].text} for the show.")
    world.say(f"The hall answered with a soft echo, as if the room itself was listening.")

    world.para()
    apply_effect(world, eel, world.facts["effect"], prop, narrate=True)
    world.say(f"But {chief.id} noticed that the {prop.label} was getting {world.facts['effect'].risk}.")
    eel.memes["worry"] += 1
    chief.memes["care"] += 1
    world.say(f'{chief.id} said, "Let’s choose a kinder sound so the {prop.label} can stay lovely."')

    world.para()
    tool = select_tool(world.facts["effect"], prop)
    if tool is not None:
        safe = world.add(Entity(
            id=tool.id, kind="tool", type="tool", label=tool.label,
            phrase=tool.phrase, protective=True, plural=tool.plural,
            guards={world.facts["effect"].risk},
        ))
        world.active_tool = safe.id
        eel.memes["joy"] += 1
        chief.memes["pride"] += 1
        world.say(f"{chief.id} brought out {tool.phrase}.")
        world.say(f'{eel.id} tried the new cue, "{world.facts["effect"].safe_cue}"')
        world.say(f"The sound felt warm and round, like a hug made of music.")
        world.say(f"{eel.id} grinned, and {chief.id} grinned too.")
        world.say(f"By the end, the {prop.label} was still fine, and the show sounded bright.")
        eel.memes["relief"] += 1
        chief.memes["closeness"] += 1
    else:
        pass


SETTINGS = {
    "tide_hall": Setting(place="the tide hall", indoor=True, affords={"show"}),
    "shell_stage": Setting(place="the shell stage by the water", indoor=False, affords={"show"}),
    "kelp_room": Setting(place="the kelp room", indoor=True, affords={"show"}),
}

SOUNDS = {
    "splish": SoundEffect(
        id="splish", name="splish", text="splish-splash", cue="Splish! Splash!",
        risk="worn", safe_cue="plip-plip", tags={"shell", "paper"},
    ),
    "clang": SoundEffect(
        id="clang", name="clang", text="clang-a-ling", cue="Clang! Clang!",
        risk="dusty", safe_cue="clink-clink", tags={"glass", "shell"},
    ),
    "whoosh": SoundEffect(
        id="whoosh", name="whoosh", text="whoosh-woosh", cue="Whoosh!",
        risk="worn", safe_cue="swish-swish", tags={"cloth", "paper"},
    ),
    "pitter": SoundEffect(
        id="pitter", name="pitter", text="pitter-patter", cue="Pitter-patter!",
        risk="dusty", safe_cue="pat-pat", tags={"paper", "shell"},
    ),
}

PROPS = {
    "shell": Prop(id="shell", label="shell bell", phrase="a bright shell-bell chime", region="hands", kind="shell"),
    "paper": Prop(id="paper", label="paper card", phrase="a fluttery paper rustle", region="hands", kind="paper"),
    "cloth": Prop(id="cloth", label="cloth banner", phrase="a soft cloth swish", region="wall", kind="cloth"),
    "glass": Prop(id="glass", label="glass cup", phrase="a tiny glass tink", region="hands", kind="glass"),
}

TOOLS = [
    Tool(id="soft_shell", label="a soft shell striker", phrase="a soft shell striker", helps="gentle sound", guards={"shell"}),
    Tool(id="silk_fin", label="a silk fin glove", phrase="a silk fin glove", helps="gentle sound", guards={"cloth", "paper"}),
    Tool(id="foam_paddle", label="a foam paddle", phrase="a foam paddle", helps="gentle sound", guards={"glass", "shell"}),
]

EEL_NAMES = ["Nori", "Milo", "Pip", "Luna", "Tavi", "Wren", "Ari", "Sora"]
CHIEF_NAMES = ["Chief Maris", "Chief Coral", "Chief Tula", "Chief Brine"]
TRAITS = ["gentle", "brave", "curious", "kind", "hopeful"]


@dataclass
class StoryParams:
    place: str
    effect: str
    prop: str
    eel_name: str
    chief_name: str
    trait: str
    seed: Optional[int] = None
    @property
    def meters(self):
        if "_meters" not in self.__dict__:
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if "_memes" not in self.__dict__:
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if "_tags" not in self.__dict__:
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        return None


def valid_combos() -> list[tuple[str, str, str]]:
    combos = []
    for place, setting in SETTINGS.items():
        for effect_id, effect in SOUNDS.items():
            for prop_id, prop in PROPS.items():
                if effect_risk(effect, prop) and select_tool(effect, prop):
                    combos.append((place, effect_id, prop_id))
    return combos


def generation_prompts(world: World) -> list[str]:
    f = world.facts
    return [
        f'Write a heartwarming story for a young child about an eel and a chief who make "{f["effect"].text}" sound effects.',
        f"Tell a gentle tale where {f['eel'].id} wants a bigger sound, but {f['chief'].id} helps keep the {f['prop'].label} safe.",
        f"Write a short, cozy story that includes the sound effect {f['effect'].cue} and ends with everyone smiling.",
    ]


def story_qa(world: World) -> list[QAItem]:
    f = world.facts
    eel = _safe_fact(world, f, "eel")
    chief = _safe_fact(world, f, "chief")
    prop = _safe_fact(world, f, "prop")
    effect = _safe_fact(world, f, "effect")
    return [
        QAItem(
            question=f"Who loved making sound effects in the story?",
            answer=f"{eel.id} did. {eel.id} was a little eel who loved making sound effects with {eel.pronoun('possessive')} {prop.label}.",
        ),
        QAItem(
            question=f"Why did {chief.id} ask for a kinder sound?",
            answer=f"{chief.id} asked because the {prop.label} was getting {effect.risk}, and {chief.id} wanted it to stay lovely for the show.",
        ),
        QAItem(
            question=f"What did they use to make the sound safe?",
            answer=f"They used {(f.get('tool') or next(iter(TOOLS.values()))).phrase}, which helped make a gentle sound without hurting the {prop.label}.",
        ),
        QAItem(
            question=f"How did {eel.id} feel at the end?",
            answer=f"{eel.id} felt happy and relieved, and {chief.id} felt proud too. They finished the show with a warm, cozy feeling.",
        ),
    ]


def world_knowledge_qa(world: World) -> list[QAItem]:
    return [
        QAItem(
            question="What is an eel?",
            answer="An eel is a long, slippery fish-like animal that can glide through water.",
        ),
        QAItem(
            question="Who is a chief?",
            answer="A chief is a leader who helps guide a group and make careful choices.",
        ),
        QAItem(
            question="What are sound effects?",
            answer="Sound effects are special sounds made to match a story, a play, or a game.",
        ),
    ]


def format_qa(sample: StorySample) -> str:
    lines = ["== Prompts =="]
    for i, p in enumerate(sample.prompts, 1):
        lines.append(f"{i}. {p}")
    lines.append("")
    lines.append("== Story QA ==")
    for item in sample.story_qa:
        lines.append(f"Q: {item.question}")
        lines.append(f"A: {item.answer}")
    lines.append("")
    lines.append("== World QA ==")
    for item in sample.world_qa:
        lines.append(f"Q: {item.question}")
        lines.append(f"A: {item.answer}")
    return "\n".join(lines)


def dump_trace(world: World) -> str:
    out = ["--- world trace ---"]
    for e in list(world.entities.values()):
        m = {k: v for k, v in e.meters.items() if v}
        mm = {k: v for k, v in e.memes.items() if v}
        bits = []
        if m:
            bits.append(f"meters={m}")
        if mm:
            bits.append(f"memes={mm}")
        if e.protective:
            bits.append(f"guards={sorted(e.guards)}")
        out.append(f"  {e.id}: {e.type} {' '.join(bits)}")
    return "\n".join(out)


ASP_RULES = r"""
effect_risk(E,P) :- sound(E), prop(P), tag(E,K), kind(P,K).
valid_combo(Place,E,P) :- setting(Place), effect(E), prop(P), effect_risk(E,P), has_tool(E,P).
has_tool(E,P) :- tag(E,K), guards(T,K), prop(P).
"""

def asp_facts() -> str:
    import storyworlds.asp as asp
    lines = []
    for sid in SETTINGS:
        lines.append(asp.fact("setting", sid))
    for eid, e in SOUNDS.items():
        lines.append(asp.fact("sound", eid))
        for t in sorted(e.tags):
            lines.append(asp.fact("tag", eid, t))
    for pid, p in PROPS.items():
        lines.append(asp.fact("prop", pid))
        lines.append(asp.fact("kind", pid, p.kind))
    for tool in TOOLS:
        lines.append(asp.fact("tool", tool.id))
        for g in sorted(tool.guards):
            lines.append(asp.fact("guards", tool.id, g))
    return "\n".join(lines)


def asp_program(show: str) -> str:
    return f"{asp_facts()}\n{ASP_RULES}\n{show}\n"


def asp_valid_combos() -> list[tuple]:
    import storyworlds.asp as asp
    model = asp.one_model(asp_program("#show valid_combo/3."))
    return sorted(set(asp.atoms(model, "valid_combo")))


def asp_verify() -> int:
    py = set(valid_combos())
    cl = set(asp_valid_combos())
    if py == cl:
        print(f"OK: ASP matches Python ({len(py)} combos).")
        return 0
    print("MISMATCH:")
    if py - cl:
        print(" only in python:", sorted(py - cl))
    if cl - py:
        print(" only in asp:", sorted(cl - py))
    return 1


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="A heartwarming eel-chief sound-effects storyworld.")
    ap.add_argument("--place", choices=SETTINGS)
    ap.add_argument("--effect", choices=SOUNDS)
    ap.add_argument("--prop", choices=PROPS)
    ap.add_argument("--name")
    ap.add_argument("--chief")
    ap.add_argument("--trait", choices=TRAITS)
    ap.add_argument("-n", type=int, default=1)
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--trace", action="store_true")
    ap.add_argument("--qa", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--asp", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--show-asp", action="store_true")
    return ap


def resolve_params(args: argparse.Namespace, rng: random.Random) -> StoryParams:
    if getattr(args, "effect", None) and getattr(args, "prop", None):
        if not (effect_risk(_safe_lookup(SOUNDS, getattr(args, "effect", None)), _safe_lookup(PROPS, getattr(args, "prop", None))) and select_tool(_safe_lookup(SOUNDS, getattr(args, "effect", None)), _safe_lookup(PROPS, getattr(args, "prop", None)))):
            return _fallback_storyparams(args, rng, StoryParams, globals())
    combos = [c for c in valid_combos()
              if (getattr(args, "place", None) is None or c[0] == getattr(args, "place", None))
              and (getattr(args, "effect", None) is None or c[1] == getattr(args, "effect", None))
              and (getattr(args, "prop", None) is None or c[2] == getattr(args, "prop", None))]
    if not combos:
        return _fallback_storyparams(args, rng, StoryParams, globals())
    place, effect, prop = rng.choice(list(combos))
    return StoryParams(
        place=place,
        effect=effect,
        prop=prop,
        eel_name=getattr(args, "name", None) or rng.choice(EEL_NAMES),
        chief_name=getattr(args, "chief", None) or rng.choice(CHIEF_NAMES),
        trait=getattr(args, "trait", None) or rng.choice(TRAITS),
    )


def generate(params: StoryParams) -> StorySample:
    world = World(_safe_lookup(SETTINGS, params.place))
    eel = world.add(Entity(id=params.eel_name, kind="character", type="eel"))
    chief = world.add(Entity(id=params.chief_name, kind="character", type="chief"))
    prop_def = _safe_lookup(PROPS, params.prop)
    prop = world.add(Entity(id=prop_def.id, kind="prop", type=prop_def.kind, label=prop_def.label, phrase=prop_def.phrase))
    effect = _safe_lookup(SOUNDS, params.effect)
    tool = _safe_lookup(TOOLS, 0)

    world.facts.update(eel=eel, chief=chief, prop=prop, effect=effect, tool=tool, place=params.place)
    build_scene(world, eel, chief, prop)
    return StorySample(
        params=params,
        story=world.render(),
        prompts=generation_prompts(world),
        story_qa=story_qa(world),
        world_qa=world_knowledge_qa(world),
        world=world,
    )


def emit(sample: StorySample, *, trace: bool = False, qa: bool = False, header: str = "") -> None:
    if header:
        print(header)
    print(sample.story)
    if trace and sample.world is not None:
        print(dump_trace(sample.world))
    if qa:
        print()
        print(format_qa(sample))


CURATED = [
    StoryParams(place="tide_hall", effect="splish", prop="shell", eel_name="Pip", chief_name="Chief Maris", trait="gentle"),
    StoryParams(place="shell_stage", effect="whoosh", prop="cloth", eel_name="Nori", chief_name="Chief Coral", trait="curious"),
    StoryParams(place="kelp_room", effect="pitter", prop="paper", eel_name="Luna", chief_name="Chief Tula", trait="hopeful"),
]


def main() -> None:
    args = build_parser().parse_args()
    if getattr(args, "show_asp", None):
        print(asp_program("#show valid_combo/3."))
        return
    if getattr(args, "verify", None):
        sys.exit(asp_verify())
    if getattr(args, "asp", None):
        triples = asp_valid_combos()
        print(f"{len(triples)} compatible combos:\n")
        for t in triples:
            print(" ", t)
        return

    base_seed = getattr(args, "seed", None) if getattr(args, "seed", None) is not None else random.randrange(2 ** 31)
    samples: list[StorySample] = []

    if getattr(args, "all", None):
        samples = [generate(p) for p in CURATED]
    else:
        seen = set()
        i = 0
        while len(samples) < getattr(args, "n", None) and i < max(getattr(args, "n", None) * 50, 50):
            seed = base_seed + i
            i += 1
            try:
                params = resolve_params(args, random.Random(seed))
            except StoryError:
                continue
            params.seed = seed
            sample = generate(params)
            if sample.story in seen:
                continue
            seen.add(sample.story)
            samples.append(sample)

    if getattr(args, "json", None):
        if len(samples) == 1:
            print(samples[0].to_json())
        else:
            print(json.dumps([s.to_dict() for s in samples], indent=2, ensure_ascii=False))
        return

    for i, sample in enumerate(samples):
        header = ""
        if getattr(args, "all", None):
            p = sample.params
            header = f"### {p.eel_name}: {p.effect} at {p.place}"
        elif len(samples) > 1:
            header = f"### variant {i + 1}"
        emit(sample, trace=getattr(args, "trace", None), qa=getattr(args, "qa", None), header=header)
        if i < len(samples) - 1:
            print("\n" + "=" * 70 + "\n")


if __name__ == "__main__":
    main()
