#!/usr/bin/env python3
"""
A standalone storyworld for a tiny mythic tale of an ember carried through dusk.

Premise:
- A small keeper must proceed on a journey with a living ember.
- The ember can be steadied or lost depending on the vessel, weather, and path.
- Suspense comes from the ember's fading heat and the long walk ahead.
- Foreshadowing comes from old signs: a crack in the sky, a warning raven, a
  remembered proverb, or a second ember waiting in reserve.

The world models physical meters and emotional memes. The story is generated by
simulating state transitions rather than swapping nouns into a frozen template.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import random
import sys
from dataclasses import dataclass, field
from typing import Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from results import QAItem, StoryError, StorySample  # noqa: E402


# ---------------------------------------------------------------------------
# World data
# ---------------------------------------------------------------------------
THRESHOLD = 1.0
EMBER_GLOW_MIN = 1.0
EMBER_SAFE = 2.0
FORESHADOW_MIN = 1.0


@dataclass
class Entity:
    id: str
    kind: str = "thing"  # "character" | "thing"
    type: str = "thing"
    label: str = ""
    phrase: str = ""
    owner: Optional[str] = None
    caretaker: Optional[str] = None
    carried_by: Optional[str] = None
    protected: bool = False
    meters: dict[str, float] = field(default_factory=dict)
    memes: dict[str, float] = field(default_factory=dict)

    def pronoun(self, case: str = "subject") -> str:
        female = {"girl", "mother", "woman", "sister", "aunt"}
        male = {"boy", "father", "man", "brother", "uncle"}
        if self.type in female:
            return {"subject": "she", "object": "her", "possessive": "her"}[case]
        if self.type in male:
            return {"subject": "he", "object": "him", "possessive": "his"}[case]
        return {"subject": "it", "object": "it", "possessive": "its"}[case]


@dataclass
class Setting:
    place: str = "the valley"
    path: str = "the stony path"
    weather: str = "windy"
    dark: bool = True
    affords: set[str] = field(default_factory=set)


@dataclass
class Vessel:
    id: str
    label: str
    phrase: str
    guards: set[str]
    covers_glow: bool
    safe_in_wind: bool
    safe_in_rain: bool
    carries: str
    tail: str


@dataclass
class StoryParams:
    setting: str
    vessel: str
    keeper: str
    helper: str
    weather: str
    seed: Optional[int] = None


class World:
    def __init__(self, setting: Setting) -> None:
        self.setting = setting
        self.entities: dict[str, Entity] = {}
        self.paragraphs: list[list[str]] = [[]]
        self.fired: set[tuple] = set()
        self.facts: dict = {}

    def add(self, ent: Entity) -> Entity:
        self.entities[ent.id] = ent
        return ent

    def get(self, eid: str) -> Entity:
        return self.entities[eid]

    def say(self, text: str) -> None:
        if text:
            self.paragraphs[-1].append(text)

    def para(self) -> None:
        if self.paragraphs[-1]:
            self.paragraphs.append([])

    def render(self) -> str:
        return "\n\n".join(" ".join(p) for p in self.paragraphs if p)

    def copy(self) -> "World":
        clone = World(self.setting)
        clone.entities = copy.deepcopy(self.entities)
        clone.paragraphs = [[]]
        clone.fired = set(self.fired)
        clone.facts = dict(self.facts)
        return clone

    def characters(self) -> list[Entity]:
        return [e for e in self.entities.values() if e.kind == "character"]

    def is_protected(self, vessel_id: str) -> bool:
        vessel = self.entities[vessel_id]
        return vessel.protected


# ---------------------------------------------------------------------------
# Registries
# ---------------------------------------------------------------------------
SETTINGS = {
    "valley": Setting(place="the valley", path="the stony path", weather="windy", dark=True, affords={"carry"}),
    "woods": Setting(place="the old woods", path="the root-woven trail", weather="windy", dark=True, affords={"carry"}),
    "river": Setting(place="the river bank", path="the narrow bank path", weather="rainy", dark=True, affords={"carry"}),
}

VESSELS = {
    "bowl": Vessel(
        id="bowl",
        label="a clay bowl",
        phrase="a clay bowl with high sides",
        guards={"wind"},
        covers_glow=False,
        safe_in_wind=False,
        safe_in_rain=True,
        carries="held the ember in a clay bowl",
        tail="kept the bowl cupped against the wind",
    ),
    "lantern": Vessel(
        id="lantern",
        label="a lantern",
        phrase="a lantern with a glass belly",
        guards={"wind", "rain"},
        covers_glow=True,
        safe_in_wind=True,
        safe_in_rain=True,
        carries="carried the ember in a lantern",
        tail="walked with the lantern shielded by careful hands",
    ),
    "pinebox": Vessel(
        id="pinebox",
        label="a pine box",
        phrase="a little pine box with a carved lid",
        guards={"wind"},
        covers_glow=True,
        safe_in_wind=True,
        safe_in_rain=False,
        carries="carried the ember in a pine box",
        tail="kept the lid closed but not tight enough for rain",
    ),
}

KEEPERS = [
    ("girl", "girl", "Mira"),
    ("boy", "boy", "Eli"),
    ("girl", "girl", "Nora"),
    ("boy", "boy", "Tomas"),
]

HELPERS = [
    ("mother", "mother", "a mother"),
    ("father", "father", "a father"),
    ("grandmother", "woman", "a grandmother"),
    ("old_sage", "man", "an old sage"),
]

# ---------------------------------------------------------------------------
# Poetry / mythic instruments
# ---------------------------------------------------------------------------
FORESHADOW_LINES = {
    "windy": "Before the first step, the reeds bent low, as if the night already knew the ember would be tested.",
    "rainy": "Before the sky darkened, one cloud hung over the hills like a closed eye, warning of rain to come.",
    "woods": "An old raven watched from a branch, as if it had seen this journey in another age.",
    "river": "The river kept a thin silver voice, and the keeper remembered that water and fire are old enemies.",
    "valley": "The valley floor held the last light like a secret, and even the stones seemed to listen.",
}

SUSPENSE_LINES = [
    "With every step, the ember trembled, small as a heartbeat in the dark.",
    "The path went on and on, and the keeper could feel the glow weakening in the vessel.",
    "The wind found every crack it could, whispering that the ember might not last.",
]

MYTH_OPENINGS = [
    "Long ago, when the hills still remembered the names of stars,",
    "In the old days, when fire was treated like a guest from the sky,",
    "Once, in a valley where even the stones had stories,",
]

MYTH_ENDINGS = [
    "And so the ember reached its home, and the night learned again how to glow.",
    "Thus the hearth woke, and the village kept its warmth through the dark hours.",
    "From that night on, the people said the path itself had remembered the fire.",
]


# ---------------------------------------------------------------------------
# ASP twin
# ---------------------------------------------------------------------------
ASP_RULES = r"""
place(Valley) :- setting(Valley).
place(Woods) :- setting(Woods).
place(River) :- setting(River).

ember_safe(P, V) :- setting(P), vessel(V), guards(V, wind), guards(V, rain).
ember_safe(P, V) :- setting(P), vessel(V), guards(V, wind), not rain_setting(P).
ember_risky(P, V) :- setting(P), vessel(V), not ember_safe(P, V).

story_valid(P, V) :- setting(P), vessel(V), affords(P, carry), ember_risky(P, V).
"""


def asp_facts() -> str:
    import asp

    lines: list[str] = []
    for sid, s in SETTINGS.items():
        lines.append(asp.fact("setting", sid))
        lines.append(asp.fact("weather", sid, s.weather))
        if s.dark:
            lines.append(asp.fact("dark", sid))
        for a in sorted(s.affords):
            lines.append(asp.fact("affords", sid, a))
    for vid, v in VESSELS.items():
        lines.append(asp.fact("vessel", vid))
        for g in sorted(v.guards):
            lines.append(asp.fact("guards", vid, g))
        if v.covers_glow:
            lines.append(asp.fact("covers_glow", vid))
        if v.safe_in_wind:
            lines.append(asp.fact("safe_in_wind", vid))
        if v.safe_in_rain:
            lines.append(asp.fact("safe_in_rain", vid))
    return "\n".join(lines)


def asp_program(show: str) -> str:
    return f"{asp_facts()}\n{ASP_RULES}\n{show}\n"


def asp_valid_combos() -> list[tuple]:
    import asp
    model = asp.one_model(asp_program("#show story_valid/2."))
    return sorted(set(asp.atoms(model, "story_valid")))


def valid_combos() -> list[tuple[str, str]]:
    out = []
    for place, setting in SETTINGS.items():
        if "carry" not in setting.affords:
            continue
        for vid, v in VESSELS.items():
            risky = not (v.safe_in_wind and (v.safe_in_rain or setting.weather != "rainy"))
            if risky:
                out.append((place, vid))
    return out


def asp_verify() -> int:
    py = set(valid_combos())
    cl = set(asp_valid_combos())
    if py == cl:
        print(f"OK: clingo gate matches valid_combos() ({len(py)} combos).")
        return 0
    print("MISMATCH between clingo and valid_combos():")
    if py - cl:
        print("  only in python:", sorted(py - cl))
    if cl - py:
        print("  only in clingo:", sorted(cl - py))
    return 1


# ---------------------------------------------------------------------------
# Story mechanics
# ---------------------------------------------------------------------------
def build_world(params: StoryParams) -> World:
    setting = copy.deepcopy(SETTINGS[params.setting])
    setting.weather = params.weather
    world = World(setting)

    keeper_type, keeper_kind, keeper_name = next(x for x in KEEPERS if x[0] == params.keeper)
    helper_type, helper_kind, helper_label = next(x for x in HELPERS if x[0] == params.helper)
    vessel_def = VESSELS[params.vessel]

    keeper = world.add(Entity(
        id=keeper_name,
        kind="character",
        type=keeper_type,
        label=keeper_name,
        meters={"glow": 0.0},
        memes={"hope": 0.0, "fear": 0.0, "resolve": 0.0, "suspense": 0.0},
    ))
    helper = world.add(Entity(
        id="helper",
        kind="character",
        type=helper_type,
        label=helper_label,
        meters={},
        memes={"foresight": 1.0},
    ))
    ember = world.add(Entity(
        id="ember",
        kind="thing",
        type="ember",
        label="ember",
        phrase="a living ember",
        owner=keeper.id,
        caretaker=helper.id,
        carried_by=keeper.id,
        protected=False,
        meters={"glow": 3.0, "heat": 3.0, "ash": 0.0},
        memes={"hope": 1.0},
    ))
    vessel = world.add(Entity(
        id=vessel_def.id,
        kind="thing",
        type=vessel_def.id,
        label=vessel_def.label,
        phrase=vessel_def.phrase,
        owner=keeper.id,
        caretaker=keeper.id,
        carried_by=keeper.id,
        protected=True,
        meters={"glow": 0.0},
        memes={"steadiness": 1.0},
    ))

    world.facts.update(keeper=keeper, helper=helper, ember=ember, vessel=vessel, vessel_def=vessel_def)
    return world


def foreshadow(world: World) -> None:
    s = world.setting
    key = s.weather if s.weather in FORESHADOW_LINES else s.place.split()[-1]
    world.say(FORESHADOW_LINES.get(key, "The night seemed to lean toward the coming journey."))
    world.facts["foreshadowed"] = True


def open_story(world: World) -> None:
    keeper = world.facts["keeper"]
    world.say(
        f"{random.choice(MYTH_OPENINGS)} {keeper.id} was the one chosen to carry a single ember across {world.setting.place}."
    )
    world.say(
        f"{keeper.id} loved the ember, because the village hearth had gone cold and all the little lamps had failed."
    )


def helper_warning(world: World) -> None:
    helper = world.facts["helper"]
    vessel = world.facts["vessel"]
    keeper = world.facts["keeper"]
    world.say(
        f"{helper.label.capitalize()} looked at {vessel.label} and said, "
        f'"Do not hurry. A small fire can die if it is treated like a toy."'
    )
    keeper.memes["fear"] += 1.0
    keeper.memes["suspense"] += 1.0


def prepare_vessel(world: World) -> None:
    vessel = world.facts["vessel"]
    keeper = world.facts["keeper"]
    ember = world.facts["ember"]
    vessel.carried_by = keeper.id
    ember.carried_by = keeper.id
    world.say(f"{keeper.id} {world.facts['vessel_def'].carries}, then pressed both hands around it.")
    if vessel.id == "lantern":
        world.say("The glass held the light in a tiny golden prison, safe from the wind.")
    elif vessel.id == "bowl":
        world.say("The bowl was open, and the ember seemed brave but exposed.")
    else:
        world.say("The pine lid covered the glow, but the rain could still find a way in.")


def proceed(world: World) -> None:
    keeper = world.facts["keeper"]
    ember = world.facts["ember"]
    vessel = world.facts["vessel"]
    setting = world.setting

    # Physical drift
    if setting.weather == "windy":
        ember.meters["heat"] -= 0.9
        ember.meters["glow"] -= 0.7
        keeper.memes["suspense"] += 1.0
    elif setting.weather == "rainy":
        ember.meters["heat"] -= 1.1
        ember.meters["glow"] -= 0.9
        keeper.memes["fear"] += 1.0

    if vessel.id == "bowl":
        ember.meters["glow"] -= 0.4
    elif vessel.id == "pinebox":
        ember.meters["heat"] -= 0.2
    else:
        ember.meters["glow"] += 0.2

    if ember.meters["glow"] < 2.0:
        world.say(random.choice(SUSPENSE_LINES))
    if ember.meters["glow"] <= EMBER_GLOW_MIN:
        keeper.memes["fear"] += 1.0
        world.say(f"{keeper.id} could see the ember paling, like a star going behind a cloud.")


def helper_compassion(world: World) -> None:
    helper = world.facts["helper"]
    keeper = world.facts["keeper"]
    ember = world.facts["ember"]
    vessel = world.facts["vessel"]
    if vessel.id == "bowl":
        world.say(
            f"{helper.label.capitalize()} walked near and shielded the bowl with a cloak, making a small wall against the wind."
        )
        ember.meters["glow"] += 0.9
    elif vessel.id == "pinebox":
        world.say(
            f"{helper.label.capitalize()} whispered an old charm and held the lid steady so the ember would not leap out."
        )
        ember.meters["heat"] += 0.7
    else:
        world.say(
            f"{helper.label.capitalize()} touched the lantern once and nodded, knowing the glass would keep the flame from the storm."
        )
        ember.meters["glow"] += 0.5
    keeper.memes["hope"] += 1.0


def resolve(world: World) -> None:
    keeper = world.facts["keeper"]
    ember = world.facts["ember"]
    vessel = world.facts["vessel"]
    if ember.meters["glow"] >= EMBER_SAFE:
        keeper.memes["resolve"] += 1.0
        world.say(
            f"At last, the path ended, and {keeper.id} lifted the vessel toward the dark house waiting at the edge of {world.setting.place}."
        )
        world.say(
            f"The ember still lived, bright enough to wake the hearth."
        )
        world.say(
            f"{random.choice(MYTH_ENDINGS)}"
        )
    else:
        world.say(
            f"The ember had nearly gone out, but {keeper.id} cupped the last warmth until a coal could be found."
        )
        world.say(
            "Even then, the little fire remembered the road and learned to glow again."
        )


def tell_story(world: World) -> None:
    open_story(world)
    world.para()
    foreshadow(world)
    helper_warning(world)
    prepare_vessel(world)
    proceed(world)
    helper_compassion(world)
    proceed(world)
    world.para()
    resolve(world)


# ---------------------------------------------------------------------------
# QA
# ---------------------------------------------------------------------------
def generation_prompts(world: World) -> list[str]:
    keeper = world.facts["keeper"]
    vessel_def = world.facts["vessel_def"]
    return [
        "Write a short mythic story for a child about a keeper who must proceed with a living ember through the dark.",
        f"Tell a suspenseful folklore-style tale in which {keeper.id} carries an ember in {vessel_def.label} and learns whether it can survive the journey.",
        "Write a gentle myth with foreshadowing, a dangerous path, and a bright ending around an ember.",
    ]


def story_qa(world: World) -> list[QAItem]:
    keeper = world.facts["keeper"]
    vessel = world.facts["vessel"]
    qa = [
        QAItem(
            question=f"What was {keeper.id} carrying through the dark?",
            answer=f"{keeper.id} was carrying a living ember, hoping it would reach the hearth safely.",
        ),
        QAItem(
            question=f"Why was {vessel.label} important in the story?",
            answer=f"{vessel.label.capitalize()} mattered because it helped protect the ember on the journey.",
        ),
        QAItem(
            question="What made the middle of the story tense?",
            answer="The ember grew weaker on the road, so the keeper had to protect it before the night could take it away.",
        ),
    ]
    if world.facts["ember"].meters["glow"] >= EMBER_SAFE:
        qa.append(
            QAItem(
                question="How did the story end?",
                answer="The keeper arrived in time, and the ember was still bright enough to relight the hearth.",
            )
        )
    else:
        qa.append(
            QAItem(
                question="How did the keeper save the ember?",
                answer="The ember nearly faded, but the keeper sheltered it and found enough warmth to bring it back.",
            )
        )
    return qa


def world_knowledge_qa(world: World) -> list[QAItem]:
    return [
        QAItem(
            question="What is an ember?",
            answer="An ember is a small piece of fire that still glows after a bigger flame has died down.",
        ),
        QAItem(
            question="Why do people cover a fire from the wind?",
            answer="People cover a fire from the wind so the flame or glow does not go out too quickly.",
        ),
        QAItem(
            question="What is foreshadowing in a story?",
            answer="Foreshadowing is when a story gives an early sign that something important may happen later.",
        ),
        QAItem(
            question="What does suspense do in a story?",
            answer="Suspense makes the reader wonder what will happen next and feel worried or excited.",
        ),
    ]


def format_qa(sample: StorySample) -> str:
    lines = ["== (1) Generation prompts -- asks that would produce this story =="]
    for i, p in enumerate(sample.prompts, 1):
        lines.append(f"{i}. {p}")
    lines.append("")
    lines.append("== (2) Story questions -- answerable from the story text ==")
    for item in sample.story_qa:
        lines.append(f"Q: {item.question}")
        lines.append(f"A: {item.answer}")
    lines.append("")
    lines.append("== (3) World-knowledge questions -- child level, no story needed ==")
    for item in sample.world_qa:
        lines.append(f"Q: {item.question}")
        lines.append(f"A: {item.answer}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def dump_trace(world: World) -> str:
    lines = ["--- world model state ---"]
    for e in world.entities.values():
        meters = {k: round(v, 3) for k, v in e.meters.items() if v}
        memes = {k: round(v, 3) for k, v in e.memes.items() if v}
        bits = []
        if meters:
            bits.append(f"meters={meters}")
        if memes:
            bits.append(f"memes={memes}")
        if e.carried_by:
            bits.append(f"carried_by={e.carried_by}")
        lines.append(f"  {e.id:8} ({e.type:8}) {' '.join(bits)}")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="A mythic ember storyworld.")
    ap.add_argument("--setting", choices=SETTINGS.keys())
    ap.add_argument("--vessel", choices=VESSELS.keys())
    ap.add_argument("--keeper", choices=[k[0] for k in KEEPERS])
    ap.add_argument("--helper", choices=[h[0] for h in HELPERS])
    ap.add_argument("--weather", choices=["windy", "rainy"])
    ap.add_argument("-n", type=int, default=1)
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--trace", action="store_true")
    ap.add_argument("--qa", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--asp", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--show-asp", action="store_true")
    return ap


def resolve_params(args: argparse.Namespace, rng: random.Random) -> StoryParams:
    setting = args.setting or rng.choice(list(SETTINGS.keys()))
    vessel = args.vessel or rng.choice(list(VESSELS.keys()))
    keeper = args.keeper or rng.choice([k[0] for k in KEEPERS])
    helper = args.helper or rng.choice([h[0] for h in HELPERS])
    weather = args.weather or SETTINGS[setting].weather
    if (setting, vessel) not in valid_combos():
        raise StoryError("No valid combination matches the given options.")
    return StoryParams(setting=setting, vessel=vessel, keeper=keeper, helper=helper, weather=weather)


def generate(params: StoryParams) -> StorySample:
    world = build_world(params)
    tell_story(world)
    return StorySample(
        params=params,
        story=world.render(),
        prompts=generation_prompts(world),
        story_qa=story_qa(world),
        world_qa=world_knowledge_qa(world),
        world=world,
    )


def emit(sample: StorySample, *, trace: bool = False, qa: bool = False, header: str = "") -> None:
    if header:
        print(header)
    print(sample.story)
    if trace and sample.world is not None:
        print(dump_trace(sample.world))
    if qa:
        print()
        print(format_qa(sample))


CURATED = [
    StoryParams(setting="valley", vessel="lantern", keeper="keeper", helper="mother", weather="windy"),
    StoryParams(setting="woods", vessel="pinebox", keeper="keeper", helper="old_sage", weather="windy"),
    StoryParams(setting="river", vessel="bowl", keeper="keeper", helper="father", weather="rainy"),
]


def main() -> None:
    args = build_parser().parse_args()

    if args.show_asp:
        print(asp_program("#show story_valid/2."))
        return
    if args.verify:
        sys.exit(asp_verify())
    if args.asp:
        import asp
        model = asp.one_model(asp_program("#show story_valid/2."))
        triples = sorted(set(asp.atoms(model, "story_valid")))
        print(f"{len(triples)} compatible combos:")
        for t in triples:
            print("  ", t)
        return

    base_seed = args.seed if args.seed is not None else random.randrange(2**31)
    samples: list[StorySample] = []

    if args.all:
        samples = [generate(p) for p in CURATED]
    else:
        seen: set[str] = set()
        i = 0
        while len(samples) < args.n and i < max(50, args.n * 50):
            seed = base_seed + i
            i += 1
            try:
                params = resolve_params(args, random.Random(seed))
            except StoryError as err:
                print(err)
                return
            params.seed = seed
            sample = generate(params)
            if sample.story in seen:
                continue
            seen.add(sample.story)
            samples.append(sample)

    if args.json:
        if len(samples) == 1:
            print(samples[0].to_json())
        else:
            print(json.dumps([s.to_dict() for s in samples], indent=2, ensure_ascii=False))
        return

    for i, sample in enumerate(samples):
        header = ""
        if args.all:
            p = sample.params
            header = f"### {p.setting} / {p.vessel}"
        elif len(samples) > 1:
            header = f"### variant {i + 1}"
        emit(sample, trace=args.trace, qa=args.qa, header=header)
        if i < len(samples) - 1:
            print("\n" + "=" * 70 + "\n")


if __name__ == "__main__":
    main()
