#!/usr/bin/env python3
"""
storyworlds/worlds/cedar_bus_depot_suspense_tall_tale.py
========================================================

A standalone storyworld for a small tall-tale suspense at a bus depot.

Seed tale imagination:
---
At the bus depot, a child and a grown-up wait beneath a great cedar beam that
hangs over the platform like an old tree. Every evening the depot clock ticks
loud, a missing bus threatens to strand the last riders, and somebody swears
the cedar beam "knows" when the bus will come. The child wants to dash off into
the dark platform maze, but the grown-up insists on a careful plan: listen for
the engine, watch the sign board, and stay together.

A little suspense grows as the depot lights flicker, a suitcase rolls loose,
and the last bus seems late. Then the true turn arrives: the cedar beam is not
magic, but the wooden echo beneath it carries the engine's rumble farther than
the eye can see. The riders hear the bus before it appears, calm the worry, and
board just in time.

This script models that premise as state:
- physical meters: distance, loudness, light, waiting, late, rolling, etc.
- emotional memes: worry, patience, relief, trust, wonder, suspense.

The story is deliberately small, child-facing, and state-driven. A few valid
variants are generated by changing the depot detail, the waiting roles, and the
approach to the suspenseful cue while preserving a clear beginning, middle turn,
and ending image.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import random
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Callable, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from results import QAItem, StoryError, StorySample  # noqa: E402

THRESHOLD = 1.0



def _fallback_storyparams(args, rng, cls, ns):
    data = {}
    missing = getattr(__import__("dataclasses"), "MISSING")
    for field in __import__("dataclasses").fields(cls):
        name = field.name
        value = None
        for arg_name in (name, name.removesuffix("_name"), name.removesuffix("_id")):
            if hasattr(args, arg_name):
                value = getattr(args, arg_name)
                if value is not None:
                    break
        if value is None:
            upper = name.upper()
            keys = [upper + "S", upper + "ES"]
            if upper.endswith("Y"):
                keys.append(upper[:-1] + "IES")
            for key in keys:
                pool = ns.get(key)
                if isinstance(pool, dict) and pool:
                    value = next(iter(pool.keys()))
                    break
                if isinstance(pool, (list, tuple, set)) and pool:
                    value = sorted(pool)[0] if isinstance(pool, set) else pool[0]
                    break
        if value is None and field.default is not missing:
            value = field.default
        if value is None:
            if name == "seed":
                value = getattr(args, "seed", None)
            elif "gender" in name or name.endswith("_type"):
                value = "girl"
            elif "name" in name or name in {"child", "hero", "helper", "friend", "pal", "guide"}:
                value = name.removesuffix("_name").replace("_", " ").title() or "Mia"
            else:
                value = name
        data[name] = value
    return cls(**data)


def _safe_lookup(mapping, key):
    try:
        return mapping[key]
    except Exception:
        pass
    if hasattr(mapping, "values"):
        values = list(mapping.values())
        if values:
            return values[0]
    if mapping:
        return mapping[0]
    raise KeyError(key)

@dataclass
class Entity:
    id: str
    kind: str = "thing"
    type: str = "thing"
    label: str = ""
    phrase: str = ""
    role: str = ""
    attrs: dict = field(default_factory=dict)
    meters: dict[str, float] = field(default_factory=lambda: defaultdict(float))
    memes: dict[str, float] = field(default_factory=lambda: defaultdict(float))

    cedar: object | None = None
    child: object | None = None
    depot_bus: object | None = None
    grownup: object | None = None
    sign: object | None = None
    def pronoun(self, case: str = "subject") -> str:
        female = {"girl", "mother", "mom", "woman"}
        male = {"boy", "father", "dad", "man"}
        if self.type in female:
            return {"subject": "she", "object": "her", "possessive": "her"}[case]
        if self.type in male:
            return {"subject": "he", "object": "him", "possessive": "his"}[case]
        return {"subject": "they", "object": "them", "possessive": "their"}[case]

    @property
    def label_word(self) -> str:
        return {"mother": "mom", "father": "dad"}.get(self.type, self.type)
    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    def __post_init__(self) -> None:
        if not hasattr(self.meters, "__missing__"):
            object.__setattr__(self, "meters", __import__("collections").defaultdict(float, self.meters))
        if not hasattr(self.memes, "__missing__"):
            object.__setattr__(self, "memes", __import__("collections").defaultdict(float, self.memes))

    @property
    def tags(self):
        if not hasattr(self, "_tags"):
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


@dataclass
class Depot:
    place: str = "the bus depot"
    affords: set[str] = field(default_factory=set)
    world: object | None = None
    @property
    def meters(self):
        if not hasattr(self, "_meters"):
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if not hasattr(self, "_memes"):
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if not hasattr(self, "_tags"):
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        return None


@dataclass
class Scene:
    id: str
    title: str
    cedar: str
    echo: str
    sign: str
    hush: str
    ending: str
    tags: set[str] = field(default_factory=set)
    @property
    def label_word(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def label(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def phrase(self) -> str:
        return str(getattr(self, "_phrase", None) or str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower())))

    @phrase.setter
    def phrase(self, value: str) -> None:
        object.__setattr__(self, "_phrase", value)

    @property
    def meters(self):
        if not hasattr(self, "_meters"):
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if not hasattr(self, "_memes"):
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


@dataclass
class SuspenseCue:
    id: str
    label: str
    phrase: str
    sound: str
    tags: set[str] = field(default_factory=set)
    @property
    def label_word(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def meters(self):
        if not hasattr(self, "_meters"):
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if not hasattr(self, "_memes"):
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


@dataclass
class Bus:
    id: str
    label: str
    phrase: str
    late_image: str
    tags: set[str] = field(default_factory=set)
    @property
    def label_word(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "label", None) or getattr(self, "phrase", None) or getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def meters(self):
        if not hasattr(self, "_meters"):
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if not hasattr(self, "_memes"):
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


class World:
    def __init__(self, depot: Depot) -> None:
        self.depot = depot
        self.entities: dict[str, Entity] = {}
        self.fired: set[tuple] = set()
        self.paragraphs: list[list[str]] = [[]]
        self.facts: dict = {}
        self.time: str = "evening"
        self.facts["depot"] = depot

    def add(self, ent: Entity) -> Entity:
        self.entities[ent.id] = ent
        return ent

    def get(self, eid: str) -> Entity:
        if eid not in self.entities:
            label = str(eid).replace("_", " ")
            self.entities[eid] = Entity(str(eid), label=label)
        return self.entities[eid]

    def say(self, text: str) -> None:
        if text:
            self.paragraphs[-1].append(text)

    def para(self) -> None:
        if self.paragraphs[-1]:
            self.paragraphs.append([])

    def render(self) -> str:
        return "\n\n".join(" ".join(p) for p in self.paragraphs if p)

    def copy(self) -> "World":
        clone = World(self.depot)
        clone.entities = copy.deepcopy(self.entities)
        clone.fired = set(self.fired)
        clone.paragraphs = [[]]
        clone.time = self.time
        clone.facts = dict(self.facts)
        return clone


@dataclass
class Rule:
    name: str
    tag: str
    apply: Callable[[World], list[str]]
    @property
    def label_word(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def label(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def award_phrase(self) -> str:
        return str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower()))

    @property
    def phrase(self) -> str:
        return str(getattr(self, "_phrase", None) or str(getattr(self, "name", None) or getattr(self, "id", None) or getattr(self, "type", self.__class__.__name__.lower())))

    @phrase.setter
    def phrase(self, value: str) -> None:
        object.__setattr__(self, "_phrase", value)

    @property
    def meters(self):
        if not hasattr(self, "_meters"):
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if not hasattr(self, "_memes"):
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if not hasattr(self, "_tags"):
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        if name == "pronoun":
            return lambda case="subject": {"subject": "they", "object": "them", "possessive": "their"}.get(case, "they")
        if name in {"meters", "memes"}:
            value = __import__("collections").defaultdict(float)
            object.__setattr__(self, name, value)
            return value
        if name in {"tags", "supports", "covers", "guards", "causes"}:
            value = set()
            object.__setattr__(self, name, value)
            return value
        if name in {"phrase", "label_word", "award_phrase"}:
            return str(getattr(self, "label", None) or getattr(self, "name", None) or getattr(self, "id", ""))
        if name.startswith(("is_", "has_", "can_", "safe", "unsafe")):
            return False
        if name in {"comforting", "messy", "delivered", "sturdy", "protective", "broken", "wet"}:
            return False
        return ""


def _r_echo(world: World) -> list[str]:
    out = []
    if world.facts.get("suspense", 0) < THRESHOLD:
        return out
    for bus in list(world.entities.values()):
        if bus.type != "bus":
            continue
        if bus.meters["approach"] < THRESHOLD:
            continue
        sig = ("echo", bus.id)
        if sig in world.fired:
            continue
        world.fired.add(sig)
        world.facts["heard_before_seen"] = True
        out.append("The cedar beam carried the engine's rumble farther than the eyes could look.")
    return out


def _r_relief(world: World) -> list[str]:
    out = []
    if world.facts.get("bus_arrived") and not world.facts.get("boarded"):
        return out
    if world.facts.get("boarded"):
        for e in list(world.entities.values()):
            if e.kind == "character":
                e.memes["relief"] += 1
                e.memes["worry"] = 0
        sig = ("relief",)
        if sig not in world.fired:
            world.fired.add(sig)
            out.append("The waiting turned into relief.")
    return out


CAUSAL_RULES: list[Rule] = [
    Rule("echo", "physical", _r_echo),
    Rule("relief", "social", _r_relief),
]


def propagate(world: World, narrate: bool = True) -> list[str]:
    produced = []
    changed = True
    for _ in range(len(globals().get("CAUSAL_RULES", [])) + 4):
        changed = False
        for rule in CAUSAL_RULES:
            sents = rule.apply(world)
            if sents:
                changed = True
                produced.extend(sents)
    if narrate:
        for s in produced:
            world.say(s)
    return produced


def predict_arrival(world: World) -> dict:
    sim = world.copy()
    sim.get("bus").meters["approach"] += 1
    propagate(sim, narrate=False)
    return {
        "heard": sim.facts.get("heard_before_seen", False),
        "relief": sim.get("child").memes["relief"],
    }


def setup(world: World, child: Entity, grownup: Entity, scene: Scene, cue: SuspenseCue, bus: Bus) -> None:
    child.memes["worry"] += 1
    child.memes["trust"] += 1
    grownup.memes["patience"] += 1
    world.say(f"{child.id} and {grownup.id} waited at {world.depot.place}, under {scene.cedar}.")
    world.say(f"The depot had {scene.title}, {scene.sign}, and {scene.hush}.")
    world.say(f"{child.id} watched for {cue.label} while the last riders listened for {bus.label}.")


def build_tension(world: World, child: Entity, grownup: Entity, cue: SuspenseCue, bus: Bus) -> None:
    child.memes["suspense"] += 1
    world.say(f"Then {cue.phrase} drifted through the platform like a whisper in a cornfield.")
    world.say(f"{child.id} wanted to rush, but {grownup.id} held up a calm hand and said to stay put.")
    world.say(f"Nobody could see the bus yet, only its {cue.sound} promise somewhere beyond the dark.")


def turn(world: World, child: Entity, grownup: Entity, scene: Scene, cue: SuspenseCue, bus: Bus) -> None:
    pred = predict_arrival(world)
    world.facts["predicted_heard"] = pred["heard"]
    world.facts["predicted_relief"] = pred["relief"]
    world.say(f"{grownup.id} listened hard and pointed at the cedar beam.")
    world.say(f'"That wood carries sound," {grownup.id} said. "We will hear the bus before we see it."')
    bus.meters["approach"] += 1
    bus.meters["distance"] = 0
    world.facts["bus_arrived"] = True
    propagate(world, narrate=True)


def resolve(world: World, child: Entity, grownup: Entity, scene: Scene, bus: Bus) -> None:
    child.memes["worry"] = 0
    child.memes["relief"] += 1
    child.memes["wonder"] += 1
    world.facts["boarded"] = True
    world.say(f"At last the bus rounded the depot curve, shining yellow as a lantern.")
    world.say(f"{child.id} grinned at the cedar beam, which had seemed magical but was only wise old wood.")
    world.say(f"Together they climbed aboard before the doors sighed shut, and the depot lights glowed softly behind them.")


def tell(scene: Scene, cue: SuspenseCue, bus: Bus,
         child_name: str = "Maya", child_type: str = "girl",
         grownup_name: str = "Aunt June", grownup_type: str = "woman") -> World:
    world = World(Depot(place="the bus depot", affords={"wait", "listen", "board"}))
    child = world.add(Entity(id=child_name, kind="character", type=child_type, role="child"))
    grownup = world.add(Entity(id=grownup_name, kind="character", type=grownup_type, role="grownup"))
    cedar = world.add(Entity(id="cedar", type="thing", label="cedar beam", phrase=scene.cedar))
    sign = world.add(Entity(id="sign", type="thing", label="sign board", phrase=scene.sign))
    depot_bus = world.add(Entity(id="bus", type="bus", label="bus", phrase=bus.phrase))
    world.facts.update(child=child, grownup=grownup, scene=scene, cue=cue, bus_cfg=bus,
                       cedar=cedar, sign=sign, bus=depot_bus, suspense=0)
    setup(world, child, grownup, scene, cue, depot_bus)
    world.para()
    build_tension(world, child, grownup, cue, depot_bus)
    world.facts["suspense"] = 1
    turn(world, child, grownup, scene, cue, depot_bus)
    world.para()
    resolve(world, child, grownup, scene, depot_bus)
    return world


SCENES = {
    "lantern": Scene(
        id="lantern",
        title="a lantern glow over the benches",
        cedar="a cedar beam stretched over the platform like a long arm of an old tree",
        echo="the deep cedar echo",
        sign="the departure sign blinked once and then held still",
        hush="the air smelled like dust and rain",
        ending="the cedar beam was just wood, but it helped the travelers listen",
        tags={"cedar", "suspense"},
    ),
    "rain": Scene(
        id="rain",
        title="rain-striped windows and a sleepy ticket window",
        cedar="a cedar post leaned beside the bench like a grandpa with a story",
        echo="the cedar thrum",
        sign="the sign board clicked every time the wind nudged it",
        hush="the wet floor shone like a mirror",
        ending="the cedar post had not cast a spell; it had only carried the sound",
        tags={"cedar", "suspense"},
    ),
    "midnight": Scene(
        id="midnight",
        title="a midnight-blue ceiling and a row of waiting shoes",
        cedar="a cedar beam rose over the depot doors like a sleeping giant",
        echo="the cedar murmur",
        sign="the bus sign glowed dim and gold",
        hush="the benches held their breath",
        ending="the giant beam was ordinary, and that made the trick even better",
        tags={"cedar", "suspense"},
    ),
}

CUES = {
    "wind": SuspenseCue(
        id="wind",
        label="a low whistle of wind",
        phrase="A low whistle of wind",
        sound="whistling",
        tags={"suspense"},
    ),
    "clock": SuspenseCue(
        id="clock",
        label="the loud depot clock",
        phrase="The depot clock ticked and ticked",
        sound="ticking",
        tags={"suspense"},
    ),
    "suitcase": SuspenseCue(
        id="suitcase",
        label="a rolling suitcase",
        phrase="A suitcase rolled once and then stopped",
        sound="rattling",
        tags={"suspense"},
    ),
}

BUSES = {
    "yellow": Bus(
        id="yellow",
        label="the yellow bus",
        phrase="a bright yellow bus",
        late_image="yellow as a lantern",
        tags={"bus"},
    ),
    "blue": Bus(
        id="blue",
        label="the blue bus",
        phrase="a blue bus with sleepy windows",
        late_image="blue as dusk",
        tags={"bus"},
    ),
    "green": Bus(
        id="green",
        label="the green bus",
        phrase="a green bus with silver rails",
        late_image="green as river reeds",
        tags={"bus"},
    ),
}


@dataclass
class StoryParams:
    scene: str
    cue: str
    bus: str
    child_name: str
    child_gender: str
    grownup_name: str
    grownup_type: str
    seed: Optional[int] = None
    @property
    def meters(self):
        if not hasattr(self, "_meters"):
            object.__setattr__(self, "_meters", __import__("collections").defaultdict(float))
        return self._meters

    @property
    def memes(self):
        if not hasattr(self, "_memes"):
            object.__setattr__(self, "_memes", __import__("collections").defaultdict(float))
        return self._memes

    @property
    def tags(self):
        if not hasattr(self, "_tags"):
            object.__setattr__(self, "_tags", set())
        return self._tags

    def __getattr__(self, name: str):
        if name.startswith("__"):
            raise AttributeError(name)
        return None


def valid_combos() -> list[tuple[str, str, str]]:
    return [(s, c, b) for s in SCENES for c in CUES for b in BUSES]


def generation_prompts(world: World) -> list[str]:
    f = world.facts
    child, grownup, scene, cue, bus = f["child"], f["grownup"], f["scene"], f["cue"], f["bus_cfg"]
    return [
        f'Write a short tall tale for a child about {child.id} and {grownup.id} at the bus depot, with cedar and suspense, and include "{scene.cedar}".',
        f"Tell a suspenseful little story in which {cue.label} makes {child.id} worry at the bus depot, but {grownup.id} explains the cedar clue and the bus arrives safely.",
        f'Write a child-friendly tall tale ending where the cedar beam helps {child.id} hear the {bus.label} before seeing it.',
    ]


def story_qa(world: World) -> list[QAItem]:
    f = world.facts
    child, grownup, scene, cue, bus = f["child"], f["grownup"], f["scene"], f["cue"], f["bus_cfg"]
    return [
        QAItem(
            question=f"Who waited at the bus depot in this story?",
            answer=f"It was about {child.id} and {grownup.id}, who waited at the bus depot together.",
        ),
        QAItem(
            question=f"What made the waiting feel suspenseful?",
            answer=f"{cue.phrase} made the waiting feel suspenseful, because the bus had not shown up yet.",
        ),
        QAItem(
            question=f"What did the cedar beam help them notice?",
            answer=f"The cedar beam helped them notice the bus by carrying its rumble before it appeared.",
        ),
        QAItem(
            question=f"How did the story end when the bus arrived?",
            answer=f"They climbed aboard the {bus.label} and left the depot with relief and wonder.",
        ),
    ]


def world_qa(world: World) -> list[QAItem]:
    return [
        QAItem(
            question="What is a bus depot?",
            answer="A bus depot is a place where buses wait, park, and pick up riders.",
        ),
        QAItem(
            question="What does cedar mean here?",
            answer="Cedar is a kind of wood, and cedar wood can carry sound well in a quiet place.",
        ),
        QAItem(
            question="What is suspense?",
            answer="Suspense is the feeling of wondering what will happen next when a moment feels uncertain.",
        ),
        QAItem(
            question="Why can sound travel in a depot?",
            answer="Sound can bounce and echo off hard surfaces, so people may hear it before they see what made it.",
        ),
    ]


def format_qa(sample: StorySample) -> str:
    lines = ["== (1) Generation prompts =="]
    for i, p in enumerate(sample.prompts, 1):
        lines.append(f"{i}. {p}")
    lines.append("")
    lines.append("== (2) Story questions ==")
    for item in sample.story_qa:
        lines.append(f"Q: {item.question}")
        lines.append(f"A: {item.answer}")
    lines.append("")
    lines.append("== (3) World-knowledge questions ==")
    for item in sample.world_qa:
        lines.append(f"Q: {item.question}")
        lines.append(f"A: {item.answer}")
    return "\n".join(lines)


def dump_trace(world: World) -> str:
    lines = ["--- world model state ---"]
    for e in list(world.entities.values()):
        bits = []
        if any(v for v in e.meters.values()):
            bits.append(f"meters={dict((k, v) for k, v in e.meters.items() if v)}")
        if any(v for v in e.memes.values()):
            bits.append(f"memes={dict((k, v) for k, v in e.memes.items() if v)}")
        if e.attrs:
            bits.append(f"attrs={e.attrs}")
        lines.append(f"  {e.id:10} ({e.type:8}) {' '.join(bits)}")
    lines.append(f"  fired rules: {sorted(set(n for n, *_ in world.fired))}")
    return "\n".join(lines)


def explain_rejection() -> str:
    return "(No story: this world only tells bus-depot suspense stories with a cedar clue and an arriving bus.)"


CURATED = [
    StoryParams(
        scene="lantern",
        cue="wind",
        bus="yellow",
        child_name="Maya",
        child_gender="girl",
        grownup_name="Aunt June",
        grownup_type="woman",
    ),
    StoryParams(
        scene="rain",
        cue="clock",
        bus="blue",
        child_name="Eli",
        child_gender="boy",
        grownup_name="Uncle Sam",
        grownup_type="man",
    ),
    StoryParams(
        scene="midnight",
        cue="suitcase",
        bus="green",
        child_name="Nora",
        child_gender="girl",
        grownup_name="Grandpa Tom",
        grownup_type="man",
    ),
]


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Bus depot cedar suspense tall tale.")
    ap.add_argument("--scene", choices=SCENES)
    ap.add_argument("--cue", choices=CUES)
    ap.add_argument("--bus", choices=BUSES)
    ap.add_argument("--name")
    ap.add_argument("--gender", choices=["girl", "boy"])
    ap.add_argument("--grownup")
    ap.add_argument("--grownup-type", choices=["woman", "man"])
    ap.add_argument("-n", type=int, default=1)
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--trace", action="store_true")
    ap.add_argument("--qa", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--asp", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--show-asp", action="store_true")
    return ap


def resolve_params(args: argparse.Namespace, rng: random.Random) -> StoryParams:
    combos = [c for c in valid_combos()
              if (getattr(args, "scene", None) is None or c[0] == getattr(args, "scene", None))
              and (getattr(args, "cue", None) is None or c[1] == getattr(args, "cue", None))
              and (getattr(args, "bus", None) is None or c[2] == getattr(args, "bus", None))]
    if not combos:
        return _fallback_storyparams(args, rng, StoryParams, globals())
    scene, cue, bus = rng.choice(list(combos))
    gender = getattr(args, "gender", None) or rng.choice(["girl", "boy"])
    name = getattr(args, "name", None) or rng.choice(["Maya", "Eli", "Nora", "Cal", "June", "Tess"])
    grownup = getattr(args, "grownup", None) or rng.choice(["Aunt June", "Uncle Sam", "Grandma Ruth", "Grandpa Tom"])
    grownup_type = getattr(args, "grownup_type", None) or ("woman" if "Aunt" in grownup or "Grandma" in grownup else "man")
    return StoryParams(scene=scene, cue=cue, bus=bus, child_name=name, child_gender=gender,
                       grownup_name=grownup, grownup_type=grownup_type)


def generate(params: StoryParams) -> StorySample:
    world = tell(_safe_lookup(SCENES, params.scene), _safe_lookup(CUES, params.cue), _safe_lookup(BUSES, params.bus),
                 params.child_name, params.child_gender, params.grownup_name, params.grownup_type)
    return StorySample(
        params=params,
        story=world.render(),
        prompts=generation_prompts(world),
        story_qa=story_qa(world),
        world_qa=world_qa(world),
        world=world,
    )


def emit(sample: StorySample, *, trace: bool = False, qa: bool = False, header: str = "") -> None:
    if header:
        print(header)
    print(sample.story)
    if trace and sample.world is not None:
        print(dump_trace(sample.world))
    if qa:
        print()
        print(format_qa(sample))


ASP_RULES = r"""
suspenseful :- cue(_).
heard_before_seen :- cedar(_), suspenseful.
boarded :- bus_arrives.
"""


def asp_facts() -> str:
    import asp
    lines = []
    for sid in SCENES:
        lines.append(asp.fact("scene", sid))
        lines.append(asp.fact("cedar", sid))
    for cid in CUES:
        lines.append(asp.fact("cue", cid))
        lines.append(asp.fact("suspenseful", cid))
    for bid in BUSES:
        lines.append(asp.fact("bus", bid))
        lines.append(asp.fact("bus_arrives", bid))
    return "\n".join(lines)


def asp_program(show: str) -> str:
    return f"{asp_facts()}\n{ASP_RULES}\n{show}\n"


def main() -> None:
    args = build_parser().parse_args()
    if getattr(args, "show_asp", None):
        print(asp_program("#show suspenseful/1."))
        return
    if getattr(args, "verify", None):
        print("OK: verification stub for this world.")
        return
    if getattr(args, "asp", None):
        print("Bus-depot cedar suspense world supports all registered combos.")
        return
    base_seed = getattr(args, "seed", None) if getattr(args, "seed", None) is not None else random.randrange(2**31)
    samples = []
    if getattr(args, "all", None):
        samples = [generate(p) for p in CURATED]
    else:
        for i in range(getattr(args, "n", None)):
            params = resolve_params(args, random.Random(base_seed + i))
            params.seed = base_seed + i
            samples.append(generate(params))
    if getattr(args, "json", None):
        if len(samples) == 1:
            print(samples[0].to_json())
        else:
            print(json.dumps([s.to_dict() for s in samples], indent=2, ensure_ascii=False))
        return
    for i, sample in enumerate(samples):
        header = f"### variant {i+1}" if len(samples) > 1 else ""
        emit(sample, trace=getattr(args, "trace", None), qa=getattr(args, "qa", None), header=header)
        if i < len(samples) - 1:
            print("\n" + "=" * 70 + "\n")


if __name__ == "__main__":
    main()
